import { Playfair_Display } from "next/font/google";

import "./globals.css";

const playfairDisplay = Playfair_Display({ subsets: ['latin'] });

export const metadata = {
  title: "Kevin Supa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
